### ISSUE TITLE
Дополните описание.

### ISSUE THREAD

**Issue by andrey-ilyin** [GreatHorizon/BackEnd#2]
https://github.com/GreatHorizon/BackEnd/blob/de1891fc139e92d36e1c0d7e5ef9e329b1380067/lab1/task2.txt#L6

**Comment by GreatHorizon** [comment]
Этот код означает, что данный ресурс был временно перемещен по какому-то адресу, в данном случае http://fi2.php.net/manual/ru/ (указан в заголовке Location)

**Comment by andrey-ilyin** [comment]
Принято.
