### ISSUE TITLE
Дополните описание.

### ISSUE THREAD

**Issue by andrey-ilyin** [GreatHorizon/BackEnd#4]
https://github.com/GreatHorizon/BackEnd/blob/de1891fc139e92d36e1c0d7e5ef9e329b1380067/lab1/task3.txt#L8

**Comment by GreatHorizon** [comment]
Т.к charset не указан, браузер попытался самостоятельно определить кодировку, и отобразить данные в ней, но кодировка не была подобрана правильно, т.е был использован другой набор символов для отображения нашего текста, поэтому мы получили нечитаемый текст

**Comment by andrey-ilyin** [comment]
Объяснение поверхностное. С натяжкой принимаю.
